# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim

WORKDIR /app

# Copy project metadata and README
COPY README.md pyproject.toml setup.py MANIFEST.in ./
# Copy source code and prompts
COPY src ./src
COPY prompts ./prompts

# Install runtime dependencies
RUN pip install --no-cache-dir .

# Default cmd prints help
CMD ["mcp-nps-business-enrollment", "--help"]
